# Generated by Django 6.0.2 on 2026-02-24 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(editable=False, max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_account', models.CharField(max_length=20)),
                ('sender_country', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_account', models.CharField(max_length=20)),
                ('receiver_country', models.CharField(max_length=100)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_bank', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
